<?php

declare(strict_types=1);

/*
 * CypressTestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CypressTestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use CypressTestAPILib\Models\Item;

/**
 * Builder for model Item
 *
 * @see Item
 */
class ItemBuilder
{
    /**
     * @var Item
     */
    private $instance;

    private function __construct(Item $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new item Builder object.
     */
    public static function init(
        string $id,
        string $name,
        \DateTime $date,
        \DateTime $dateTime,
        float $decimal,
        int $long,
        bool $bool,
        string $customEnum,
        array $jsonObject,
        array $animal,
        array $map
    ): self {
        return new self(
            new Item($id, $name, $date, $dateTime, $decimal, $long, $bool, $customEnum, $jsonObject, $animal, $map)
        );
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new item object.
     */
    public function build(): Item
    {
        return CoreHelper::clone($this->instance);
    }
}
