<?php

declare(strict_types=1);

/*
 * CypressTestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace CypressTestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use CypressTestAPILib\Models\MultipleArraysRequest;

/**
 * Builder for model MultipleArraysRequest
 *
 * @see MultipleArraysRequest
 */
class MultipleArraysRequestBuilder
{
    /**
     * @var MultipleArraysRequest
     */
    private $instance;

    private function __construct(MultipleArraysRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new multiple arrays request Builder object.
     */
    public static function init(array $array1): self
    {
        return new self(new MultipleArraysRequest($array1));
    }

    /**
     * Sets array 2 field.
     */
    public function array2(?array $value): self
    {
        $this->instance->setArray2($value);
        return $this;
    }

    /**
     * Initializes a new multiple arrays request object.
     */
    public function build(): MultipleArraysRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
